# Generated by Django 2.2 on 2019-12-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20180226_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewsCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
